### ISSUE TITLE
Does redux-offline design promote anti-pattern dispatch in reducer

### ISSUE THREAD

**Issue by Noitidart** [redux-offline/redux-offline#90] opened 2017-06-12 05:53 UTC
Hi there,

Because the effect to do a XHR results in an action of COMMIT or ROLLBACK does this promote the anti-pattern of doing dispatch in reducer?

For example:

1. I go offline
2. While offline, I dispatch action to API to "add customer" (this will do - `dispatch({type:API_CALL, meta:{offline:{effect: ..., commit:{type:POP, success:true}, rollback:...}}})`)
3. I dispatch action to "add order" for the customer I just created - however because step 2 action of "add customer" has not yet completed, this action will be "pending". It is waiting for the "add customer" from step 2 to finish successfully, after which it will do a dispatch with offline meta data.
4. I go online, add customer completes and triggers the "commit" `{type:POP, success:true}`. My reducer now has the need to dispatch a `resume` action for anything that was waiting for this customer

Maybe to fix this, we could set commit, and rollback in offline meta data to be action creators (functions) instead of plain actions (objects)?

**Comment by sabativi** [comment] 2017-06-19 15:50
I love this question ! 
I just got an error : 'Reducers may not dispatch action' on react-native since I am using apollo client, and sending back a mutation when connectivity is On again...
Which is normal, as optimitic UI had already modify our state, the goal of a reducer is not so clear in this case...

**Comment by pocheptsov** [comment] 2017-08-10 14:38
PR to mitigate it https://github.com/jevakallio/redux-offline/pull/106

**Comment by sorodrigo** [comment] 2017-11-07 23:03
This question has been asked multiple times. The issue is not as straightforward as adding action creators; this is mainly because functions (or promises also) are not serializable. We're still discussing the best way to tackle this.

**Comment by Noitidart** [comment] 2017-11-08 04:45
Thanks for the update @sorodrigo !

In the mean time, for others, a solution can be to use redux-saga and `yield take( action => action.type===COMMIT && ...)` for COMMIT/ROLLBACK. Then you can use `put` from the saga.

**Comment by gusgard** [comment] 2018-01-19 16:22
@Noitidart  Thanks for the idea!

**Comment by sorodrigo** [comment] 2018-01-21 17:24
Sagas aside, a PR has just been merged that returns a promise when an action is completed. This way you can `.then` or `.catch` the dispatched action. There’s a pitfalls to this. Given that promises are not serialized, this promise will only resolve/reject on the same session. If the action gets dispatched on another session the promise won’t resolve.

**Comment by Noitidart** [comment] 2018-01-22 18:58
Yea man totally @gusgard - sagas are pretty awesome. I queue up sagas and because they can be serialized we can carry between sessions using channels (i havent done this yet but thats what people tell me).

**Comment by sorodrigo** [comment] 2018-01-22 21:22
Hey @noitidart would yo be willing to  contribute? I would like to add a sagas example to the current examples app

**Comment by Noitidart** [comment] 2018-01-22 21:24
Thanks @sorodrigo ! I actually stopped using this lib and was doing my own offline via sagas. So sorry but I am very out of touch with this now. :(

**Comment by Johnafriedman** [comment] 2018-02-10 20:05
I have a similar problem. In my case the user can create a story and add a page to it. I optimistically add a page so the user can continue to work offline. The add page action accepts a callback that provides access to the story and checks if the story has completed, if not skips the network request and just adds the data to the story. The effect reconciler uses the callback, if available, to get the latest data that includes all edits to post. Please excuse my horrible noobness, in my defense the API was built before I was assigned to make it function offline. Just wanted to know how bad this solution is if anyone cares to comment.  Or maybe it would be a useful idea. Thanks!

**Comment by msmaromi** [comment] 2018-02-23 06:47
@sorodrigo could you give the example of this workaround?

**Comment by Noitidart** [comment] 2018-02-23 07:00
I found that using channels in redux-saga is far superior (more declarative, and much less code). You guys should try that out.

**Comment by sorodrigo** [comment] 2018-02-23 07:57
@Johnafriedman passing a callback to the actions won't work through sessions. A good solution for this is to use sagas, epics or other side-effects middleware libraries.

We support dispatch as a promise, so you can `.then()` when an action is performed. However, this doesn't work through sessions either. We're actually working on an in house solution that would let you chain offline actions. This is not there yet, but it's being developed.

@msmaromi About making an example, I'm not sure if you meant the passing callbacks workaround or the `redux-saga` one. If you meant a sagas examples, we really want that in our examples application https://github.com/redux-offline/redux-offline/issues/173 , I haven't got the time to learn sagas and implement it myself, so we are happy if you or anyone wants to make a PR to add a working solution for chaining with sagas. The issue mentioned has some comments that might help you start.

**Comment by Noitidart** [comment] 2018-02-23 08:10
With sagas let me give the way I do it. I haven't settled a one size fits all solution, so it's hard for me to write one definitve exmaple. I can describe a one size fits all solution though, that I use across my works.

With sags I do this:

* I found that with redux-offline we had a single queue, but really we have multiple. For instance "create item" "edit item" "delete item" "create order for item" "edit order for item" "delete order for item" these all go into same queue. We also get a queue per item id (optimistic id until got submitted to server). And then we have our other obvious queues (like: "create user", "edit user", "delete user" go into another queue)
* Create a `channel` for each "queue". Each channel holds the actions, which are serializable of course (redux actions are, unless you put in some weird data, dont do this, file data should be stored in file system and only its path should be in store).
* The channel watches its queue, and as the action is stored into the queue, it also goes into the channel.
* When an action comes into the queue, check if another action is pending that is the same. Such as "edit" or "create" and merge the datas. If "edit" came in, but a "create" existed. If the "create" is hanging for offline, or server down, or no auth, merge the edit data to the "create". If/once we are only and "create" fails, then it should also check the `channel` to see if any other related fetch. For instance if "edit" then merge it and try it again. If "delete", then cancel the "create". If "delete" and create had succeed then the "delete" should continue to do the fetch.
  * Whenever these merge or fetch completions happen, the action is removed from the queue - this makes the session persistance almost free (its not free because we did create a store entry/reducer of "queues")
  * On consequent startup, have a saga that recreates channels with actions from the queues.

**Comment by sorodrigo** [comment] 2018-02-23 08:31
That sounds like a good approach, but it adds a lot of complexity to handling actions. I'm thinking of a live code application example that doesn't have to worry about merging actions. Say you dispatch a create and then an edit/delete, as of right now those actions would be stored in order and would be executed in order.
Of course it would be nice to be super smart about it and just dispatch an _edited_ create or not dispatch anything if it was later deleted, but it might not be essential for the app to work.

My idea is more about letting the user chain an action (offline or not), after a commit or rollback action has been performed. So say you dispatch a `CREATE_SHARED_CALENDAR` action, it would be awesome if when the API returns with a commit and you have the new `calendarId`, you could dispatch a `SEND_CALENDAR_INVITE`. This way ensure your not inviting before the calendar even exists in the API.

**Comment by msmaromi** [comment] 2018-02-23 13:58
@sorodrigo okey thanks, I'll try it

**Comment by Noitidart** [comment] 2018-02-25 14:16
@sorodrigo oh wow I think you're totally right! Its always awesome to share, there is an awesome synergy! So glad I took the time to do that, and very appreciative that you read it and thought about it deeply!

**Comment by sorodrigo** [comment] 2018-02-25 14:39
No problem! If you're willing to implement this, we could add it to @redux-offline org as an external plugin. I think the idea is great and a lot of people would be interested in using it.

**Comment by Noitidart** [comment] 2018-02-25 14:41
I totally wish I could but it's tough because it's hard for me to get motivated to work on something I won't be personally using. :( Forgive me there please. :(

**Comment by sorodrigo** [comment] 2018-02-25 14:42
No biggie, totally understand.

**Comment by msmaromi** [comment] 2018-02-26 03:29
Because of the dispatch is promise. I can `put.resolve` in sagas so it will wait the action fulfilled then continue the execution.

**Comment by sorodrigo** [comment] 2018-02-26 07:17
You can also `.then()` but this feature won't persist across sessions.

**Comment by msmaromi** [comment] 2018-02-27 03:34
Sagas actually solve that

**Comment by sorodrigo** [comment] 2018-05-09 18:45
See https://github.com/redux-offline/redux-offline/blob/develop/docs/recipes/redux-saga.md

**Closed as completed by sorodrigo** 2018-05-09 18:45 UTC
