### ISSUE TITLE
Problem with "@react-native-community/netinfo": "4.6.1" - getCurrentState

### ISSUE THREAD

**Issue by FranciscoCHT** [redux-offline/redux-offline#381] opened 2020-01-03 09:32 UTC
### Store config
```js
import { applyMiddleware, createStore, compose } from 'redux';
import thunkMiddleware from 'redux-thunk';
import reducer from './reducer';

import { offline } from '@redux-offline/redux-offline';
import offlineConfig from '@redux-offline/redux-offline/lib/defaults';

export const store = createStore(reducer, {}, compose(
    applyMiddleware(thunkMiddleware),
    offline(offlineConfig)
));
```
### Try using the versions
    "@react-native-community/netinfo": "4.6.1",
    "@redux-offline/redux-offline": "2.5.2-native.1",

### Message error

Due to the bug with deprecated methods in the last version of @react-native-community/netinfo ^5.0.0, which doesn't work yet with the native version of Redux Offline, I decided to **install version 4.6.1 of NetInfo**, which still has the deprecated methods.
But, when run on Android, throws an error. 

The error occurs when you use:
```
"@react-native-community/netinfo": "4.6.1",
"@redux-offline/redux-offline": "2.5.2-native.1",
```

![81172383_572250756656486_5590522594332770304_n](https://user-images.githubusercontent.com/9930150/71715683-086dc000-2df1-11ea-8511-436d640b8710.jpg)

### React-Native Info
```
System:
    OS: Windows 10 10.0.18362
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 6.75 GB / 15.94 GB
  Binaries:
    Node: 12.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
```

**Comment by jasonleibowitz** [comment] 2020-01-05 16:14
Could this be a duplicate of #373? Looks like it'll be fixed when the next release is published to NPM that includes #372.

**Comment by FranciscoCHT** [comment] 2020-01-05 23:24
> Could this be a duplicate of #373? Looks like it'll be fixed when the next release is published to NPM that includes #372.

Shouldn't be. If I understand correctly, that fix is for compatibility with the new version of netinfo (because the deprecated methods have been removed). Here I used a older version of netinfo, which still has the deprecated methods.

**Comment by eugenemlee** [comment] 2020-01-07 04:28
Try using:
`"@react-native-community/netinfo": "4.7.0"`

**Comment by FranciscoCHT** [comment] 2020-01-07 19:42
> Try using:
> `"@react-native-community/netinfo": "4.7.0"`

Tried, same error.

**Comment by betoharres** [comment] 2020-01-15 01:05
Updating `redux-offline` fixed my warning with `react-native-netinfo`:
```
TypeError: _netinfo.default.getConnectionInfo is not a function. (In '_netinfo.default.getConnectionInfo()', '_netinfo.default.getConnectionInfo' is undefined)
```
I love you guys <3

**Comment by FranciscoCHT** [comment] 2020-01-15 14:25
Ultimately, I had to update to the last version of NetInfo and edit the files of redux-offline by myself to make it work, since the update hadn't been published yet at the time. And now with the required update published, worked great too.

**Comment by sorodrigo** [comment] 2020-01-15 15:53
grrrreat, glad to hear that! I'm sorry for this problem, its very inconvenient. Until we change the architecture it's hard to maintain, and we haven't had the time to work on the new version.

**Closed as completed by sorodrigo** 2020-01-15 15:53 UTC

**Comment by Creativemast** [comment] 2022-11-15 14:10
> 4.6.1

whats is your current react-offline
