### ISSUE TITLE
undefined is not an object  _reactNative.NetInfo.getConnectionInfo

### ISSUE THREAD

**Issue by Usamaliaquat123** [redux-offline/redux-offline#367] opened 2019-11-06 11:18 UTC
![Bug](https://user-images.githubusercontent.com/33973828/68293825-9444c380-00b0-11ea-9986-650b995ed0cc.png)

### Configure Store
```
const store = createStore(
  reducers,
  {},
  compose(
    applyMiddleware(thuck),
    offline(offlineConfig),
  ),
);

```
### Run app
`react-native run-android`

### Error 
**undefined is not an object  _reactNative.NetInfo.getConnectionInfo**

**Comment by calumpeak** [comment] 2019-11-06 11:23
Duplicate of #351

**Closed as completed by calumpeak** 2019-11-06 11:23 UTC
