### ISSUE TITLE
undefined is not an object (evaluating '_reactNative.NetInfo.getConnectionInfo')

### ISSUE THREAD

**Issue by vadiraja** [redux-offline/redux-offline#334] opened 2019-07-06 23:04 UTC
error occurs at

detectNetwork.native.js
var isLegacy = typeof _reactNative.NetInfo.getConnectionInfo === 'undefined';

**Comment by calumpeak** [comment] 2019-07-15 16:23
Duplicate of #323

**Closed as completed by calumpeak** 2019-07-15 16:23 UTC
